config/routes.rb
Rails.application.routes.draw do

  root :to => "users#top"

  get "home/about" => "users#about"

  devise_for :users

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#follower"
    get "followings" => "relationships#following"
  end

  get "search" => "search#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_commetns, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationship, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :active_relationship, source: :follower
  has_many :follower_user, through: :passive_relationships, source: :following
  
  attachment :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def follow(id)
    active_relationship.create(follower_id: id)
  end

  def unfollow(id)
    unfollow = active_relationship.find_by(follower_id: id)
    unfollow.destroy
  end

  def following?(id)
    following_user.include?(id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:index, :show, :edit, :update]

    def top
    end
  
    def about
    end
    
    def index
      @users = User.all
      @book = Book.new
      @user = current_user
    end
  
    def show
      @user = User.find(params[:id])
      @book = Book.new
      @books = @user.books.reverse_order
    end
  
    def edit
      @user = User.find(params[:id])
      unless @user == current_user # 条件が偽なら実行
        redirect_to user_path(current_user)
      end
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to user_path(current_user)
      else
          render :edit
      end
    end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
    <% users.each do |user| %>
        <tr>
            <td>
            <% unless user.profile_image.present?  %>
                <%= image_tag "no_image_square.jpg", format: 'jpeg', size: "40x40", alt: "No image icon" %>
            <% else %>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "50x50",alt: "profile image" %>
            <% end %>
            </td>
            <td><%= user.name %></td>
            <td>
                <% unless current_user == user %>
                    <% if current_user.following?(user) %>
                        <%= button_to user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" do %>
                            <i class="glyphicon glyphicon-minus"></i>
                        <% end %>
                    <% else %>
                        <%= button_to user_relationships_path(user.id), method: :post, class: "btn-sm btn-success" do %>
                                <i class="glyphicon glyphicon-plus"></i>
                        <% end %>
                    <% end %>
                <% end %>
            </td>
            <td><%= link_to "Show", user_path(user)%></td>
        </tr> 
    <% end %>
    </tbody>
</table>

app/views/users/_user_info.html.erb
<h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', class: "attachment user profile_image", fallback: "no_image_square.jpg", alt: "profile_image" %>
    <table class="table">
        <tbody>
            <tr>
                <th>name</th>
                <th><%= user.name %></th>
            </tr>
             <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
            <tr>
                <th>Follow</th>
                <th>
                    <%= link_to user_followings_path(user.id) do %>
                        <%= user.following_user.count %>
                    <% end %>
                </th>
            </tr>
            <tr>
                <th>Follower</th>
                <th>
                    <%= link_to user_followers_path(user.id) do %>
                        <%= user.follower_user.count %>
                    <% end %>
                </th>            
            </tr>
        </tbody>
    </table>
        <div class="row">
            <%= link_to edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" do %>
            <% end %>
        </div>
        <div class="row">
            <% unless current_user == user %>
                <% if current_user.following?(user) %>
                    <%= button_to user_relationships_path(user.id), method: :delete, class: "col-xs-12 btn-sm btn-danger" do %>
                        <i class="glyphicon glyphicon-minus"></i>
                    <% end %>
                <% else %>
                    <%= button_to user_relationships_path(user.id), method: :post, class: "col-xs-12 btn-sm btn-success" do %>
                            <i class="glyphicon glyphicon-plus"></i>
                    <% end %>
                <% end %>
            <% end %>
        </div>

    <h2>New book</h2>
    <%= form_for(book) do |f| %>
        <div class="field row">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "col-xs-12 book_title"%>
        </div>
        <div class="field row">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class: "col-xs-12 book_body" %>
        </div>
        <div class="actions row">
            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        </div>
    <% end %>

app/views/users/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= render 'layouts/errors', model: @user %>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class:"name" %>
    </div>
    <div class="field">
    <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>
    <div class="field">
    <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: "introduction" %>
    </div>
    <div class="actions">             
        <%= f.submit "Update User" %>
    </div>
<% end %>

app/views/users/index.html.erb
<%= render 'layouts/errors', model: @book %>

<div class="row">
    <div class = "col-xs-3">
        <%= render 'users/user_info', user: @user, book: @book %>
    </div>
    <div class = "col-xs-9">
        <h2>Users</h2>
        <%= render 'index', users: @users %>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/errors', model: @book %>

<div class="row">
<div class = "col-xs-3">
    <%= render 'users/user_info', user: @user, book: @book %>
</div>
    <div class = "col-xs-9">
        <%= render 'books/index', books: @books %>
    </div>
</div>

app/views/users/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
            
  </div>
</div>