config/routes.rb
Rails.application.routes.draw do

  root :to => "users#top"

  get "home/about" => "users#about"

  devise_for :users

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#follower"
    get "followings" => "relationships#following"
  end

  get "search" => "search#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

    def favorited_by?(a)
        favorites.where(user_id: a.id).exists?
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!


    def index
        @books = Book.all
        @book = Book.new
        @user = current_user
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        @books = Book.all
        if @book.save
            flash[:notice] = "You have creatad book successfully."
            redirect_to book_path(@book)
        else
            @user = current_user
            render :index
        end
    end

    def show
        @book = Book.find(params[:id])
        @book_new = Book.new
        @user = @book.user
        @comment = BookComment.new
        @comments = @book.book_comments
    end

    def edit
        @book = Book.find(params[:id])
        unless @book.user.id == current_user.id
            redirect_to "/books"            
        end
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book)
        else
            render :edit
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

private
    def book_params
        params.require(:book).permit(:title, :body)  
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<h2>Books</h2>
<table class = "table table-hover table-inverse">
    <thead>
        <tr>
            <th></th>
            <th>Titile</th>
            <th>Opinion</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "50x50", alt: "profile_image", fallback: "no_image_square.jpg"  %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <%= link_to book_path(book) do %>
                <i class="glyphicon glyphicon-comment">
                  <%= book.book_comments.count %>
                </i>
              <% end %>
            </td>
            <% if book.favorited_by?(current_user) %>
              <td>
                <%= button_to book_favorites_path(book.id), method: :delete, style: "background-color:white; border: none;" do %>
                  <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></i>
                  <%= book.favorites.count %>いいね！
                <% end %>            
              </td>
            <% else %>
              <td>
                <%= button_to book_favorites_path(book.id), method: :post, style: "background-color:white; border: none;" do %>
                  <i class="glyphicon glyphicon-heart" aria-hidden="true" ></i>
                  <%= book.favorites.count %>いいね！
                <% end %>
              </td>
            <% end %>
        </tr> 
      <% end %>
    </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <%= render 'layouts/errors', model: @book %>
        <%= form_for(@book) do |f| %>
            <div class="field row">
                <label for="book_title">Title</label>
                <%= f.text_field :title, class: "col-xs-12 book_title" %>
            </div>
            <div class="field row">
                <label for="book_opinion">Opinion</label>
                <%= f.text_area :body, class: "col-xs-12 book_body" %>
            </div>
            <div class="actions row">
                <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
            </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <a href="/books" class="back">Back</a>
    </div>
    <div class = "col-md-3"></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', model: @book %>
<div class="row">
<div class = "col-xs-3">
    <%= render 'users/user_info', user: @user, book: @book %>
</div>
    <div class = "col-xs-9">
        <%= render 'index', books: @books, book_find: @book%>
    </div>
</div>

app/views/books/show.html.erb
<%= render 'layouts/errors', model: @book %>

<div class="row">
    <div class = "col-xs-3">
        <%= render 'users/user_info', user: @user, book: @book_new %>
    </div>
    <div class = "col-xs-9">
        <h2>Book detail</h2>
        <table class = "table">
            <tbody>
                <tr>
                    <td>
                        <%= link_to user_path(@user) do %>
                            <%= attachment_image_tag @book.user, :profile_image, size: "100x100", fallback: "no_image_square.jpg" %>
                            <br><%= @user.name %>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to @book.title, book_path(@book)  %>
                    </td>
                    <td><%= @book.body %></td>
                    <td>
                        <div id="count_area">
                            <%= render 'book_comments/count', book: @book, comments: @comments %>
                        </div>
                    </td>
                    <% if @book.favorited_by?(current_user) %>
                        <td>
                            <%= button_to book_favorites_path(@book.id), method: :delete, style: "background-color:white; border: none;" do %>
                            <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color:red;"></i>
                            <%= @book.favorites.count %>いいね！
                            <% end %>            
                        </td>
                        <% else %>
                        <td>
                            <%= button_to book_favorites_path(@book.id), method: :post, style: "background-color:white; border: none;" do %>
                            <i class="glyphicon glyphicon-heart" aria-hidden="true" ></i>
                            <%= @book.favorites.count %>いいね！
                            <% end %>
                        </td>
                        <% end %>
                    <% if @book.user == current_user %>
                        <td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %></td>
                        <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn-sm btn-danger" %>
                    <% end %>
                </tr>
            </tbody>
        </table>

        <%# コメント一覧 %>
        <div id="comment_area">
            <%= render 'book_comments/comment', comments: @comments, comment: @comment, book: @book %>
        </div>

        <%# コメント一覧 %>

        <%# コメント記入欄 %>

        <div class="book_comments">
            <%= form_with(model: [@book, @comment]) do |f| %>
                <div class="field">
                    <%= f.text_area :comment %>
                </div>
                <div class = "action">
                    <%= f.submit "コメントする", class: "btn btn-primary" %>
                </div>
            <% end %>
        </div>

        <%# コメント記入欄 %>

    </div>
</div>