config/routes.rb
Rails.application.routes.draw do

  root :to => "users#top"

  get "home/about" => "users#about"

  devise_for :users

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followers" => "relationships#follower"
    get "followings" => "relationships#following"
  end

  get "search" => "search#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
      <h3><%= pluralize(model.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
          <% model.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnsBookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
    <header class = "navbar navbar-fixed-top navbar-inverse">
      <div class = "container">
        <nav class = "nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class = "nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to ' Users', '/users', class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to ' Books', '/books', class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          <% else %>
            <li><%= link_to ' Home', "/", class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to ' About', home_about_url, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to ' login', new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if user_signed_in? %>
      <div class="search-var" style="margin-top: 70px; text-align: center;">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.select 'range', options_for_select([['選択してください', '0'], ['User', '1'], ['Book', '2']]) %>
              <%= f.select 'match', options_for_select([["前方一致","forward"], ["後方一致","backward"], ["完全一致","perfect"], ["部分一致","partial"]]) %>
          <%= f.text_field 'search_word' %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
    <% end %>

      <div class="body">
        <div class="container">
          <p id="notice">
            <p><%= notice %></p>
          </p>
          <%= yield %>
        </div>
      </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>